/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoyProfesionalRouteImport } from './routes/soy-profesional'
import { Route as ProfesionalFundadorRouteImport } from './routes/profesional-fundador'
import { Route as PlanPresenciaRouteImport } from './routes/plan-presencia'
import { Route as MiEspacioRouteImport } from './routes/mi-espacio'
import { Route as ListaEsperaRouteImport } from './routes/lista-espera'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComunidadFundadoraOrganizacionesRouteImport } from './routes/comunidad-fundadora-organizaciones'
import { Route as ComunidadFundadoraCentrosRouteImport } from './routes/comunidad-fundadora-centros'
import { Route as ComunidadFundadoraBienvenidaRouteImport } from './routes/comunidad-fundadora-bienvenida'
import { Route as ComunidadFundadoraAccesoRouteImport } from './routes/comunidad-fundadora-acceso'
import { Route as ComunidadFundadoraRouteImport } from './routes/comunidad-fundadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MiEspacioIndexRouteImport } from './routes/mi-espacio.index'
import { Route as ProfesionalSlugRouteImport } from './routes/profesional.$slug'
import { Route as ProfesionalFreeSlugRouteImport } from './routes/profesional-free.$slug'
import { Route as MiEspacioSuscripcionRouteImport } from './routes/mi-espacio.suscripcion'
import { Route as MiEspacioPerfilRouteImport } from './routes/mi-espacio.perfil'
import { Route as MiEspacioAyudaRouteImport } from './routes/mi-espacio.ayuda'
import { Route as MiEspacioActividadesRouteImport } from './routes/mi-espacio.actividades'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as FuturoProfesionalVerificadoRouteImport } from './routes/futuro.profesional-verificado'
import { Route as FuturoPlanPresenciaRouteImport } from './routes/futuro.plan-presencia'
import { Route as FuturoCentrosOrganizadoresRouteImport } from './routes/futuro.centros-organizadores'
import { Route as DashboardTipoPerfilRouteImport } from './routes/dashboard.tipo-perfil'
import { Route as DashboardStripeRouteImport } from './routes/dashboard.stripe'
import { Route as DashboardSolicitudEnviadaRouteImport } from './routes/dashboard.solicitud-enviada'
import { Route as DashboardPerfilPublicadoRouteImport } from './routes/dashboard.perfil-publicado'
import { Route as DashboardFormularioRouteImport } from './routes/dashboard.formulario'
import { Route as AuthCrearCuentaRouteImport } from './routes/auth.crear-cuenta'
import { Route as ActividadIdRouteImport } from './routes/actividad.$id'
import { Route as MiEspacioActividadesIndexRouteImport } from './routes/mi-espacio.actividades.index'
import { Route as MiEspacioActividadesNuevaRouteImport } from './routes/mi-espacio.actividades.nueva'

const SoyProfesionalRoute = SoyProfesionalRouteImport.update({
  id: '/soy-profesional',
  path: '/soy-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalFundadorRoute = ProfesionalFundadorRouteImport.update({
  id: '/profesional-fundador',
  path: '/profesional-fundador',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPresenciaRoute = PlanPresenciaRouteImport.update({
  id: '/plan-presencia',
  path: '/plan-presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEspacioRoute = MiEspacioRouteImport.update({
  id: '/mi-espacio',
  path: '/mi-espacio',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaEsperaRoute = ListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadFundadoraOrganizacionesRoute =
  ComunidadFundadoraOrganizacionesRouteImport.update({
    id: '/comunidad-fundadora-organizaciones',
    path: '/comunidad-fundadora-organizaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraCentrosRoute =
  ComunidadFundadoraCentrosRouteImport.update({
    id: '/comunidad-fundadora-centros',
    path: '/comunidad-fundadora-centros',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraBienvenidaRoute =
  ComunidadFundadoraBienvenidaRouteImport.update({
    id: '/comunidad-fundadora-bienvenida',
    path: '/comunidad-fundadora-bienvenida',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraAccesoRoute =
  ComunidadFundadoraAccesoRouteImport.update({
    id: '/comunidad-fundadora-acceso',
    path: '/comunidad-fundadora-acceso',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraRoute = ComunidadFundadoraRouteImport.update({
  id: '/comunidad-fundadora',
  path: '/comunidad-fundadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEspacioIndexRoute = MiEspacioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MiEspacioRoute,
} as any)
const ProfesionalSlugRoute = ProfesionalSlugRouteImport.update({
  id: '/profesional/$slug',
  path: '/profesional/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalFreeSlugRoute = ProfesionalFreeSlugRouteImport.update({
  id: '/profesional-free/$slug',
  path: '/profesional-free/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEspacioSuscripcionRoute = MiEspacioSuscripcionRouteImport.update({
  id: '/suscripcion',
  path: '/suscripcion',
  getParentRoute: () => MiEspacioRoute,
} as any)
const MiEspacioPerfilRoute = MiEspacioPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MiEspacioRoute,
} as any)
const MiEspacioAyudaRoute = MiEspacioAyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => MiEspacioRoute,
} as any)
const MiEspacioActividadesRoute = MiEspacioActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => MiEspacioRoute,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoProfesionalVerificadoRoute =
  FuturoProfesionalVerificadoRouteImport.update({
    id: '/futuro/profesional-verificado',
    path: '/futuro/profesional-verificado',
    getParentRoute: () => rootRouteImport,
  } as any)
const FuturoPlanPresenciaRoute = FuturoPlanPresenciaRouteImport.update({
  id: '/futuro/plan-presencia',
  path: '/futuro/plan-presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoCentrosOrganizadoresRoute =
  FuturoCentrosOrganizadoresRouteImport.update({
    id: '/futuro/centros-organizadores',
    path: '/futuro/centros-organizadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardTipoPerfilRoute = DashboardTipoPerfilRouteImport.update({
  id: '/tipo-perfil',
  path: '/tipo-perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStripeRoute = DashboardStripeRouteImport.update({
  id: '/stripe',
  path: '/stripe',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSolicitudEnviadaRoute =
  DashboardSolicitudEnviadaRouteImport.update({
    id: '/solicitud-enviada',
    path: '/solicitud-enviada',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerfilPublicadoRoute =
  DashboardPerfilPublicadoRouteImport.update({
    id: '/perfil-publicado',
    path: '/perfil-publicado',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormularioRoute = DashboardFormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCrearCuentaRoute = AuthCrearCuentaRouteImport.update({
  id: '/auth/crear-cuenta',
  path: '/auth/crear-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadIdRoute = ActividadIdRouteImport.update({
  id: '/actividad/$id',
  path: '/actividad/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEspacioActividadesIndexRoute =
  MiEspacioActividadesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MiEspacioActividadesRoute,
  } as any)
const MiEspacioActividadesNuevaRoute =
  MiEspacioActividadesNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => MiEspacioActividadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/comunidad-fundadora-acceso': typeof ComunidadFundadoraAccesoRoute
  '/comunidad-fundadora-bienvenida': typeof ComunidadFundadoraBienvenidaRoute
  '/comunidad-fundadora-centros': typeof ComunidadFundadoraCentrosRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/mi-espacio': typeof MiEspacioRouteWithChildren
  '/plan-presencia': typeof PlanPresenciaRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/actividad/$id': typeof ActividadIdRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/dashboard/tipo-perfil': typeof DashboardTipoPerfilRoute
  '/futuro/centros-organizadores': typeof FuturoCentrosOrganizadoresRoute
  '/futuro/plan-presencia': typeof FuturoPlanPresenciaRoute
  '/futuro/profesional-verificado': typeof FuturoProfesionalVerificadoRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/mi-espacio/actividades': typeof MiEspacioActividadesRouteWithChildren
  '/mi-espacio/ayuda': typeof MiEspacioAyudaRoute
  '/mi-espacio/perfil': typeof MiEspacioPerfilRoute
  '/mi-espacio/suscripcion': typeof MiEspacioSuscripcionRoute
  '/profesional-free/$slug': typeof ProfesionalFreeSlugRoute
  '/profesional/$slug': typeof ProfesionalSlugRoute
  '/mi-espacio/': typeof MiEspacioIndexRoute
  '/mi-espacio/actividades/nueva': typeof MiEspacioActividadesNuevaRoute
  '/mi-espacio/actividades/': typeof MiEspacioActividadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/comunidad-fundadora-acceso': typeof ComunidadFundadoraAccesoRoute
  '/comunidad-fundadora-bienvenida': typeof ComunidadFundadoraBienvenidaRoute
  '/comunidad-fundadora-centros': typeof ComunidadFundadoraCentrosRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/actividad/$id': typeof ActividadIdRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/dashboard/tipo-perfil': typeof DashboardTipoPerfilRoute
  '/futuro/centros-organizadores': typeof FuturoCentrosOrganizadoresRoute
  '/futuro/plan-presencia': typeof FuturoPlanPresenciaRoute
  '/futuro/profesional-verificado': typeof FuturoProfesionalVerificadoRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/mi-espacio/ayuda': typeof MiEspacioAyudaRoute
  '/mi-espacio/perfil': typeof MiEspacioPerfilRoute
  '/mi-espacio/suscripcion': typeof MiEspacioSuscripcionRoute
  '/profesional-free/$slug': typeof ProfesionalFreeSlugRoute
  '/profesional/$slug': typeof ProfesionalSlugRoute
  '/mi-espacio': typeof MiEspacioIndexRoute
  '/mi-espacio/actividades/nueva': typeof MiEspacioActividadesNuevaRoute
  '/mi-espacio/actividades': typeof MiEspacioActividadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/comunidad-fundadora-acceso': typeof ComunidadFundadoraAccesoRoute
  '/comunidad-fundadora-bienvenida': typeof ComunidadFundadoraBienvenidaRoute
  '/comunidad-fundadora-centros': typeof ComunidadFundadoraCentrosRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/mi-espacio': typeof MiEspacioRouteWithChildren
  '/plan-presencia': typeof PlanPresenciaRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/actividad/$id': typeof ActividadIdRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/dashboard/tipo-perfil': typeof DashboardTipoPerfilRoute
  '/futuro/centros-organizadores': typeof FuturoCentrosOrganizadoresRoute
  '/futuro/plan-presencia': typeof FuturoPlanPresenciaRoute
  '/futuro/profesional-verificado': typeof FuturoProfesionalVerificadoRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/mi-espacio/actividades': typeof MiEspacioActividadesRouteWithChildren
  '/mi-espacio/ayuda': typeof MiEspacioAyudaRoute
  '/mi-espacio/perfil': typeof MiEspacioPerfilRoute
  '/mi-espacio/suscripcion': typeof MiEspacioSuscripcionRoute
  '/profesional-free/$slug': typeof ProfesionalFreeSlugRoute
  '/profesional/$slug': typeof ProfesionalSlugRoute
  '/mi-espacio/': typeof MiEspacioIndexRoute
  '/mi-espacio/actividades/nueva': typeof MiEspacioActividadesNuevaRoute
  '/mi-espacio/actividades/': typeof MiEspacioActividadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidad-fundadora'
    | '/comunidad-fundadora-acceso'
    | '/comunidad-fundadora-bienvenida'
    | '/comunidad-fundadora-centros'
    | '/comunidad-fundadora-organizaciones'
    | '/dashboard'
    | '/lista-espera'
    | '/mi-espacio'
    | '/plan-presencia'
    | '/profesional-fundador'
    | '/soy-profesional'
    | '/actividad/$id'
    | '/auth/crear-cuenta'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/dashboard/tipo-perfil'
    | '/futuro/centros-organizadores'
    | '/futuro/plan-presencia'
    | '/futuro/profesional-verificado'
    | '/invitacion/$token'
    | '/mi-espacio/actividades'
    | '/mi-espacio/ayuda'
    | '/mi-espacio/perfil'
    | '/mi-espacio/suscripcion'
    | '/profesional-free/$slug'
    | '/profesional/$slug'
    | '/mi-espacio/'
    | '/mi-espacio/actividades/nueva'
    | '/mi-espacio/actividades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidad-fundadora'
    | '/comunidad-fundadora-acceso'
    | '/comunidad-fundadora-bienvenida'
    | '/comunidad-fundadora-centros'
    | '/comunidad-fundadora-organizaciones'
    | '/dashboard'
    | '/lista-espera'
    | '/plan-presencia'
    | '/profesional-fundador'
    | '/soy-profesional'
    | '/actividad/$id'
    | '/auth/crear-cuenta'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/dashboard/tipo-perfil'
    | '/futuro/centros-organizadores'
    | '/futuro/plan-presencia'
    | '/futuro/profesional-verificado'
    | '/invitacion/$token'
    | '/mi-espacio/ayuda'
    | '/mi-espacio/perfil'
    | '/mi-espacio/suscripcion'
    | '/profesional-free/$slug'
    | '/profesional/$slug'
    | '/mi-espacio'
    | '/mi-espacio/actividades/nueva'
    | '/mi-espacio/actividades'
  id:
    | '__root__'
    | '/'
    | '/comunidad-fundadora'
    | '/comunidad-fundadora-acceso'
    | '/comunidad-fundadora-bienvenida'
    | '/comunidad-fundadora-centros'
    | '/comunidad-fundadora-organizaciones'
    | '/dashboard'
    | '/lista-espera'
    | '/mi-espacio'
    | '/plan-presencia'
    | '/profesional-fundador'
    | '/soy-profesional'
    | '/actividad/$id'
    | '/auth/crear-cuenta'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/dashboard/tipo-perfil'
    | '/futuro/centros-organizadores'
    | '/futuro/plan-presencia'
    | '/futuro/profesional-verificado'
    | '/invitacion/$token'
    | '/mi-espacio/actividades'
    | '/mi-espacio/ayuda'
    | '/mi-espacio/perfil'
    | '/mi-espacio/suscripcion'
    | '/profesional-free/$slug'
    | '/profesional/$slug'
    | '/mi-espacio/'
    | '/mi-espacio/actividades/nueva'
    | '/mi-espacio/actividades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadFundadoraRoute: typeof ComunidadFundadoraRoute
  ComunidadFundadoraAccesoRoute: typeof ComunidadFundadoraAccesoRoute
  ComunidadFundadoraBienvenidaRoute: typeof ComunidadFundadoraBienvenidaRoute
  ComunidadFundadoraCentrosRoute: typeof ComunidadFundadoraCentrosRoute
  ComunidadFundadoraOrganizacionesRoute: typeof ComunidadFundadoraOrganizacionesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListaEsperaRoute: typeof ListaEsperaRoute
  MiEspacioRoute: typeof MiEspacioRouteWithChildren
  PlanPresenciaRoute: typeof PlanPresenciaRoute
  ProfesionalFundadorRoute: typeof ProfesionalFundadorRoute
  SoyProfesionalRoute: typeof SoyProfesionalRoute
  ActividadIdRoute: typeof ActividadIdRoute
  AuthCrearCuentaRoute: typeof AuthCrearCuentaRoute
  FuturoCentrosOrganizadoresRoute: typeof FuturoCentrosOrganizadoresRoute
  FuturoPlanPresenciaRoute: typeof FuturoPlanPresenciaRoute
  FuturoProfesionalVerificadoRoute: typeof FuturoProfesionalVerificadoRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
  ProfesionalFreeSlugRoute: typeof ProfesionalFreeSlugRoute
  ProfesionalSlugRoute: typeof ProfesionalSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soy-profesional': {
      id: '/soy-profesional'
      path: '/soy-profesional'
      fullPath: '/soy-profesional'
      preLoaderRoute: typeof SoyProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional-fundador': {
      id: '/profesional-fundador'
      path: '/profesional-fundador'
      fullPath: '/profesional-fundador'
      preLoaderRoute: typeof ProfesionalFundadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-presencia': {
      id: '/plan-presencia'
      path: '/plan-presencia'
      fullPath: '/plan-presencia'
      preLoaderRoute: typeof PlanPresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-espacio': {
      id: '/mi-espacio'
      path: '/mi-espacio'
      fullPath: '/mi-espacio'
      preLoaderRoute: typeof MiEspacioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-espera': {
      id: '/lista-espera'
      path: '/lista-espera'
      fullPath: '/lista-espera'
      preLoaderRoute: typeof ListaEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-organizaciones': {
      id: '/comunidad-fundadora-organizaciones'
      path: '/comunidad-fundadora-organizaciones'
      fullPath: '/comunidad-fundadora-organizaciones'
      preLoaderRoute: typeof ComunidadFundadoraOrganizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-centros': {
      id: '/comunidad-fundadora-centros'
      path: '/comunidad-fundadora-centros'
      fullPath: '/comunidad-fundadora-centros'
      preLoaderRoute: typeof ComunidadFundadoraCentrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-bienvenida': {
      id: '/comunidad-fundadora-bienvenida'
      path: '/comunidad-fundadora-bienvenida'
      fullPath: '/comunidad-fundadora-bienvenida'
      preLoaderRoute: typeof ComunidadFundadoraBienvenidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-acceso': {
      id: '/comunidad-fundadora-acceso'
      path: '/comunidad-fundadora-acceso'
      fullPath: '/comunidad-fundadora-acceso'
      preLoaderRoute: typeof ComunidadFundadoraAccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora': {
      id: '/comunidad-fundadora'
      path: '/comunidad-fundadora'
      fullPath: '/comunidad-fundadora'
      preLoaderRoute: typeof ComunidadFundadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-espacio/': {
      id: '/mi-espacio/'
      path: '/'
      fullPath: '/mi-espacio/'
      preLoaderRoute: typeof MiEspacioIndexRouteImport
      parentRoute: typeof MiEspacioRoute
    }
    '/profesional/$slug': {
      id: '/profesional/$slug'
      path: '/profesional/$slug'
      fullPath: '/profesional/$slug'
      preLoaderRoute: typeof ProfesionalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional-free/$slug': {
      id: '/profesional-free/$slug'
      path: '/profesional-free/$slug'
      fullPath: '/profesional-free/$slug'
      preLoaderRoute: typeof ProfesionalFreeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-espacio/suscripcion': {
      id: '/mi-espacio/suscripcion'
      path: '/suscripcion'
      fullPath: '/mi-espacio/suscripcion'
      preLoaderRoute: typeof MiEspacioSuscripcionRouteImport
      parentRoute: typeof MiEspacioRoute
    }
    '/mi-espacio/perfil': {
      id: '/mi-espacio/perfil'
      path: '/perfil'
      fullPath: '/mi-espacio/perfil'
      preLoaderRoute: typeof MiEspacioPerfilRouteImport
      parentRoute: typeof MiEspacioRoute
    }
    '/mi-espacio/ayuda': {
      id: '/mi-espacio/ayuda'
      path: '/ayuda'
      fullPath: '/mi-espacio/ayuda'
      preLoaderRoute: typeof MiEspacioAyudaRouteImport
      parentRoute: typeof MiEspacioRoute
    }
    '/mi-espacio/actividades': {
      id: '/mi-espacio/actividades'
      path: '/actividades'
      fullPath: '/mi-espacio/actividades'
      preLoaderRoute: typeof MiEspacioActividadesRouteImport
      parentRoute: typeof MiEspacioRoute
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro/profesional-verificado': {
      id: '/futuro/profesional-verificado'
      path: '/futuro/profesional-verificado'
      fullPath: '/futuro/profesional-verificado'
      preLoaderRoute: typeof FuturoProfesionalVerificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro/plan-presencia': {
      id: '/futuro/plan-presencia'
      path: '/futuro/plan-presencia'
      fullPath: '/futuro/plan-presencia'
      preLoaderRoute: typeof FuturoPlanPresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro/centros-organizadores': {
      id: '/futuro/centros-organizadores'
      path: '/futuro/centros-organizadores'
      fullPath: '/futuro/centros-organizadores'
      preLoaderRoute: typeof FuturoCentrosOrganizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tipo-perfil': {
      id: '/dashboard/tipo-perfil'
      path: '/tipo-perfil'
      fullPath: '/dashboard/tipo-perfil'
      preLoaderRoute: typeof DashboardTipoPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stripe': {
      id: '/dashboard/stripe'
      path: '/stripe'
      fullPath: '/dashboard/stripe'
      preLoaderRoute: typeof DashboardStripeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/solicitud-enviada': {
      id: '/dashboard/solicitud-enviada'
      path: '/solicitud-enviada'
      fullPath: '/dashboard/solicitud-enviada'
      preLoaderRoute: typeof DashboardSolicitudEnviadaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil-publicado': {
      id: '/dashboard/perfil-publicado'
      path: '/perfil-publicado'
      fullPath: '/dashboard/perfil-publicado'
      preLoaderRoute: typeof DashboardPerfilPublicadoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/formulario': {
      id: '/dashboard/formulario'
      path: '/formulario'
      fullPath: '/dashboard/formulario'
      preLoaderRoute: typeof DashboardFormularioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/crear-cuenta': {
      id: '/auth/crear-cuenta'
      path: '/auth/crear-cuenta'
      fullPath: '/auth/crear-cuenta'
      preLoaderRoute: typeof AuthCrearCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividad/$id': {
      id: '/actividad/$id'
      path: '/actividad/$id'
      fullPath: '/actividad/$id'
      preLoaderRoute: typeof ActividadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-espacio/actividades/': {
      id: '/mi-espacio/actividades/'
      path: '/'
      fullPath: '/mi-espacio/actividades/'
      preLoaderRoute: typeof MiEspacioActividadesIndexRouteImport
      parentRoute: typeof MiEspacioActividadesRoute
    }
    '/mi-espacio/actividades/nueva': {
      id: '/mi-espacio/actividades/nueva'
      path: '/nueva'
      fullPath: '/mi-espacio/actividades/nueva'
      preLoaderRoute: typeof MiEspacioActividadesNuevaRouteImport
      parentRoute: typeof MiEspacioActividadesRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFormularioRoute: typeof DashboardFormularioRoute
  DashboardPerfilPublicadoRoute: typeof DashboardPerfilPublicadoRoute
  DashboardSolicitudEnviadaRoute: typeof DashboardSolicitudEnviadaRoute
  DashboardStripeRoute: typeof DashboardStripeRoute
  DashboardTipoPerfilRoute: typeof DashboardTipoPerfilRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFormularioRoute: DashboardFormularioRoute,
  DashboardPerfilPublicadoRoute: DashboardPerfilPublicadoRoute,
  DashboardSolicitudEnviadaRoute: DashboardSolicitudEnviadaRoute,
  DashboardStripeRoute: DashboardStripeRoute,
  DashboardTipoPerfilRoute: DashboardTipoPerfilRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MiEspacioActividadesRouteChildren {
  MiEspacioActividadesNuevaRoute: typeof MiEspacioActividadesNuevaRoute
  MiEspacioActividadesIndexRoute: typeof MiEspacioActividadesIndexRoute
}

const MiEspacioActividadesRouteChildren: MiEspacioActividadesRouteChildren = {
  MiEspacioActividadesNuevaRoute: MiEspacioActividadesNuevaRoute,
  MiEspacioActividadesIndexRoute: MiEspacioActividadesIndexRoute,
}

const MiEspacioActividadesRouteWithChildren =
  MiEspacioActividadesRoute._addFileChildren(MiEspacioActividadesRouteChildren)

interface MiEspacioRouteChildren {
  MiEspacioActividadesRoute: typeof MiEspacioActividadesRouteWithChildren
  MiEspacioAyudaRoute: typeof MiEspacioAyudaRoute
  MiEspacioPerfilRoute: typeof MiEspacioPerfilRoute
  MiEspacioSuscripcionRoute: typeof MiEspacioSuscripcionRoute
  MiEspacioIndexRoute: typeof MiEspacioIndexRoute
}

const MiEspacioRouteChildren: MiEspacioRouteChildren = {
  MiEspacioActividadesRoute: MiEspacioActividadesRouteWithChildren,
  MiEspacioAyudaRoute: MiEspacioAyudaRoute,
  MiEspacioPerfilRoute: MiEspacioPerfilRoute,
  MiEspacioSuscripcionRoute: MiEspacioSuscripcionRoute,
  MiEspacioIndexRoute: MiEspacioIndexRoute,
}

const MiEspacioRouteWithChildren = MiEspacioRoute._addFileChildren(
  MiEspacioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadFundadoraRoute: ComunidadFundadoraRoute,
  ComunidadFundadoraAccesoRoute: ComunidadFundadoraAccesoRoute,
  ComunidadFundadoraBienvenidaRoute: ComunidadFundadoraBienvenidaRoute,
  ComunidadFundadoraCentrosRoute: ComunidadFundadoraCentrosRoute,
  ComunidadFundadoraOrganizacionesRoute: ComunidadFundadoraOrganizacionesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListaEsperaRoute: ListaEsperaRoute,
  MiEspacioRoute: MiEspacioRouteWithChildren,
  PlanPresenciaRoute: PlanPresenciaRoute,
  ProfesionalFundadorRoute: ProfesionalFundadorRoute,
  SoyProfesionalRoute: SoyProfesionalRoute,
  ActividadIdRoute: ActividadIdRoute,
  AuthCrearCuentaRoute: AuthCrearCuentaRoute,
  FuturoCentrosOrganizadoresRoute: FuturoCentrosOrganizadoresRoute,
  FuturoPlanPresenciaRoute: FuturoPlanPresenciaRoute,
  FuturoProfesionalVerificadoRoute: FuturoProfesionalVerificadoRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
  ProfesionalFreeSlugRoute: ProfesionalFreeSlugRoute,
  ProfesionalSlugRoute: ProfesionalSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
