/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoyProfesionalRouteImport } from './routes/soy-profesional'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as ListaEsperaRouteImport } from './routes/lista-espera'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComunidadFundadoraRouteImport } from './routes/comunidad-fundadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlanProfesionalVerificadoRouteImport } from './routes/plan.profesional-verificado'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as DashboardStripeRouteImport } from './routes/dashboard.stripe'
import { Route as DashboardSolicitudEnviadaRouteImport } from './routes/dashboard.solicitud-enviada'
import { Route as DashboardPerfilPublicadoRouteImport } from './routes/dashboard.perfil-publicado'
import { Route as DashboardFormularioRouteImport } from './routes/dashboard.formulario'
import { Route as AuthRecuperarRouteImport } from './routes/auth.recuperar'
import { Route as AuthIniciarSesionRouteImport } from './routes/auth.iniciar-sesion'
import { Route as AuthCrearCuentaRouteImport } from './routes/auth.crear-cuenta'

const SoyProfesionalRoute = SoyProfesionalRouteImport.update({
  id: '/soy-profesional',
  path: '/soy-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaEsperaRoute = ListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadFundadoraRoute = ComunidadFundadoraRouteImport.update({
  id: '/comunidad-fundadora',
  path: '/comunidad-fundadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanProfesionalVerificadoRoute =
  PlanProfesionalVerificadoRouteImport.update({
    id: '/plan/profesional-verificado',
    path: '/plan/profesional-verificado',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStripeRoute = DashboardStripeRouteImport.update({
  id: '/stripe',
  path: '/stripe',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSolicitudEnviadaRoute =
  DashboardSolicitudEnviadaRouteImport.update({
    id: '/solicitud-enviada',
    path: '/solicitud-enviada',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerfilPublicadoRoute =
  DashboardPerfilPublicadoRouteImport.update({
    id: '/perfil-publicado',
    path: '/perfil-publicado',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormularioRoute = DashboardFormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRecuperarRoute = AuthRecuperarRouteImport.update({
  id: '/auth/recuperar',
  path: '/auth/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIniciarSesionRoute = AuthIniciarSesionRouteImport.update({
  id: '/auth/iniciar-sesion',
  path: '/auth/iniciar-sesion',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCrearCuentaRoute = AuthCrearCuentaRouteImport.update({
  id: '/auth/crear-cuenta',
  path: '/auth/crear-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/planes': typeof PlanesRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/auth/iniciar-sesion': typeof AuthIniciarSesionRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/plan/profesional-verificado': typeof PlanProfesionalVerificadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/planes': typeof PlanesRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/auth/iniciar-sesion': typeof AuthIniciarSesionRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/plan/profesional-verificado': typeof PlanProfesionalVerificadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/planes': typeof PlanesRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/auth/iniciar-sesion': typeof AuthIniciarSesionRoute
  '/auth/recuperar': typeof AuthRecuperarRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
  '/plan/profesional-verificado': typeof PlanProfesionalVerificadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidad-fundadora'
    | '/dashboard'
    | '/lista-espera'
    | '/planes'
    | '/soy-profesional'
    | '/auth/crear-cuenta'
    | '/auth/iniciar-sesion'
    | '/auth/recuperar'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/invitacion/$token'
    | '/plan/profesional-verificado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidad-fundadora'
    | '/dashboard'
    | '/lista-espera'
    | '/planes'
    | '/soy-profesional'
    | '/auth/crear-cuenta'
    | '/auth/iniciar-sesion'
    | '/auth/recuperar'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/invitacion/$token'
    | '/plan/profesional-verificado'
  id:
    | '__root__'
    | '/'
    | '/comunidad-fundadora'
    | '/dashboard'
    | '/lista-espera'
    | '/planes'
    | '/soy-profesional'
    | '/auth/crear-cuenta'
    | '/auth/iniciar-sesion'
    | '/auth/recuperar'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/invitacion/$token'
    | '/plan/profesional-verificado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadFundadoraRoute: typeof ComunidadFundadoraRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListaEsperaRoute: typeof ListaEsperaRoute
  PlanesRoute: typeof PlanesRoute
  SoyProfesionalRoute: typeof SoyProfesionalRoute
  AuthCrearCuentaRoute: typeof AuthCrearCuentaRoute
  AuthIniciarSesionRoute: typeof AuthIniciarSesionRoute
  AuthRecuperarRoute: typeof AuthRecuperarRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
  PlanProfesionalVerificadoRoute: typeof PlanProfesionalVerificadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soy-profesional': {
      id: '/soy-profesional'
      path: '/soy-profesional'
      fullPath: '/soy-profesional'
      preLoaderRoute: typeof SoyProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-espera': {
      id: '/lista-espera'
      path: '/lista-espera'
      fullPath: '/lista-espera'
      preLoaderRoute: typeof ListaEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora': {
      id: '/comunidad-fundadora'
      path: '/comunidad-fundadora'
      fullPath: '/comunidad-fundadora'
      preLoaderRoute: typeof ComunidadFundadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/profesional-verificado': {
      id: '/plan/profesional-verificado'
      path: '/plan/profesional-verificado'
      fullPath: '/plan/profesional-verificado'
      preLoaderRoute: typeof PlanProfesionalVerificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stripe': {
      id: '/dashboard/stripe'
      path: '/stripe'
      fullPath: '/dashboard/stripe'
      preLoaderRoute: typeof DashboardStripeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/solicitud-enviada': {
      id: '/dashboard/solicitud-enviada'
      path: '/solicitud-enviada'
      fullPath: '/dashboard/solicitud-enviada'
      preLoaderRoute: typeof DashboardSolicitudEnviadaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil-publicado': {
      id: '/dashboard/perfil-publicado'
      path: '/perfil-publicado'
      fullPath: '/dashboard/perfil-publicado'
      preLoaderRoute: typeof DashboardPerfilPublicadoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/formulario': {
      id: '/dashboard/formulario'
      path: '/formulario'
      fullPath: '/dashboard/formulario'
      preLoaderRoute: typeof DashboardFormularioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/recuperar': {
      id: '/auth/recuperar'
      path: '/auth/recuperar'
      fullPath: '/auth/recuperar'
      preLoaderRoute: typeof AuthRecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/iniciar-sesion': {
      id: '/auth/iniciar-sesion'
      path: '/auth/iniciar-sesion'
      fullPath: '/auth/iniciar-sesion'
      preLoaderRoute: typeof AuthIniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/crear-cuenta': {
      id: '/auth/crear-cuenta'
      path: '/auth/crear-cuenta'
      fullPath: '/auth/crear-cuenta'
      preLoaderRoute: typeof AuthCrearCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardFormularioRoute: typeof DashboardFormularioRoute
  DashboardPerfilPublicadoRoute: typeof DashboardPerfilPublicadoRoute
  DashboardSolicitudEnviadaRoute: typeof DashboardSolicitudEnviadaRoute
  DashboardStripeRoute: typeof DashboardStripeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFormularioRoute: DashboardFormularioRoute,
  DashboardPerfilPublicadoRoute: DashboardPerfilPublicadoRoute,
  DashboardSolicitudEnviadaRoute: DashboardSolicitudEnviadaRoute,
  DashboardStripeRoute: DashboardStripeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadFundadoraRoute: ComunidadFundadoraRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListaEsperaRoute: ListaEsperaRoute,
  PlanesRoute: PlanesRoute,
  SoyProfesionalRoute: SoyProfesionalRoute,
  AuthCrearCuentaRoute: AuthCrearCuentaRoute,
  AuthIniciarSesionRoute: AuthIniciarSesionRoute,
  AuthRecuperarRoute: AuthRecuperarRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
  PlanProfesionalVerificadoRoute: PlanProfesionalVerificadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
