/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SoyProfesionalRouteImport } from './routes/soy-profesional'
import { Route as ProfesionalFundadorRouteImport } from './routes/profesional-fundador'
import { Route as PlanPresenciaRouteImport } from './routes/plan-presencia'
import { Route as ListaEsperaRouteImport } from './routes/lista-espera'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComunidadFundadoraOrganizacionesRouteImport } from './routes/comunidad-fundadora-organizaciones'
import { Route as ComunidadFundadoraRouteImport } from './routes/comunidad-fundadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvitacionTokenRouteImport } from './routes/invitacion.$token'
import { Route as FuturoProfesionalVerificadoRouteImport } from './routes/futuro.profesional-verificado'
import { Route as FuturoPlanPresenciaRouteImport } from './routes/futuro.plan-presencia'
import { Route as FuturoCentrosOrganizadoresRouteImport } from './routes/futuro.centros-organizadores'
import { Route as DashboardStripeRouteImport } from './routes/dashboard.stripe'
import { Route as DashboardSolicitudEnviadaRouteImport } from './routes/dashboard.solicitud-enviada'
import { Route as DashboardPerfilPublicadoRouteImport } from './routes/dashboard.perfil-publicado'
import { Route as DashboardFormularioRouteImport } from './routes/dashboard.formulario'
import { Route as AuthCrearCuentaRouteImport } from './routes/auth.crear-cuenta'

const SoyProfesionalRoute = SoyProfesionalRouteImport.update({
  id: '/soy-profesional',
  path: '/soy-profesional',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalFundadorRoute = ProfesionalFundadorRouteImport.update({
  id: '/profesional-fundador',
  path: '/profesional-fundador',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPresenciaRoute = PlanPresenciaRouteImport.update({
  id: '/plan-presencia',
  path: '/plan-presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaEsperaRoute = ListaEsperaRouteImport.update({
  id: '/lista-espera',
  path: '/lista-espera',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadFundadoraOrganizacionesRoute =
  ComunidadFundadoraOrganizacionesRouteImport.update({
    id: '/comunidad-fundadora-organizaciones',
    path: '/comunidad-fundadora-organizaciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComunidadFundadoraRoute = ComunidadFundadoraRouteImport.update({
  id: '/comunidad-fundadora',
  path: '/comunidad-fundadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionTokenRoute = InvitacionTokenRouteImport.update({
  id: '/invitacion/$token',
  path: '/invitacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoProfesionalVerificadoRoute =
  FuturoProfesionalVerificadoRouteImport.update({
    id: '/futuro/profesional-verificado',
    path: '/futuro/profesional-verificado',
    getParentRoute: () => rootRouteImport,
  } as any)
const FuturoPlanPresenciaRoute = FuturoPlanPresenciaRouteImport.update({
  id: '/futuro/plan-presencia',
  path: '/futuro/plan-presencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FuturoCentrosOrganizadoresRoute =
  FuturoCentrosOrganizadoresRouteImport.update({
    id: '/futuro/centros-organizadores',
    path: '/futuro/centros-organizadores',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardStripeRoute = DashboardStripeRouteImport.update({
  id: '/stripe',
  path: '/stripe',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSolicitudEnviadaRoute =
  DashboardSolicitudEnviadaRouteImport.update({
    id: '/solicitud-enviada',
    path: '/solicitud-enviada',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPerfilPublicadoRoute =
  DashboardPerfilPublicadoRouteImport.update({
    id: '/perfil-publicado',
    path: '/perfil-publicado',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardFormularioRoute = DashboardFormularioRouteImport.update({
  id: '/formulario',
  path: '/formulario',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCrearCuentaRoute = AuthCrearCuentaRouteImport.update({
  id: '/auth/crear-cuenta',
  path: '/auth/crear-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/futuro/centros-organizadores': typeof FuturoCentrosOrganizadoresRoute
  '/futuro/plan-presencia': typeof FuturoPlanPresenciaRoute
  '/futuro/profesional-verificado': typeof FuturoProfesionalVerificadoRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/futuro/centros-organizadores': typeof FuturoCentrosOrganizadoresRoute
  '/futuro/plan-presencia': typeof FuturoPlanPresenciaRoute
  '/futuro/profesional-verificado': typeof FuturoProfesionalVerificadoRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comunidad-fundadora': typeof ComunidadFundadoraRoute
  '/comunidad-fundadora-organizaciones': typeof ComunidadFundadoraOrganizacionesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/lista-espera': typeof ListaEsperaRoute
  '/plan-presencia': typeof PlanPresenciaRoute
  '/profesional-fundador': typeof ProfesionalFundadorRoute
  '/soy-profesional': typeof SoyProfesionalRoute
  '/auth/crear-cuenta': typeof AuthCrearCuentaRoute
  '/dashboard/formulario': typeof DashboardFormularioRoute
  '/dashboard/perfil-publicado': typeof DashboardPerfilPublicadoRoute
  '/dashboard/solicitud-enviada': typeof DashboardSolicitudEnviadaRoute
  '/dashboard/stripe': typeof DashboardStripeRoute
  '/futuro/centros-organizadores': typeof FuturoCentrosOrganizadoresRoute
  '/futuro/plan-presencia': typeof FuturoPlanPresenciaRoute
  '/futuro/profesional-verificado': typeof FuturoProfesionalVerificadoRoute
  '/invitacion/$token': typeof InvitacionTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comunidad-fundadora'
    | '/comunidad-fundadora-organizaciones'
    | '/dashboard'
    | '/lista-espera'
    | '/plan-presencia'
    | '/profesional-fundador'
    | '/soy-profesional'
    | '/auth/crear-cuenta'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/futuro/centros-organizadores'
    | '/futuro/plan-presencia'
    | '/futuro/profesional-verificado'
    | '/invitacion/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comunidad-fundadora'
    | '/comunidad-fundadora-organizaciones'
    | '/dashboard'
    | '/lista-espera'
    | '/plan-presencia'
    | '/profesional-fundador'
    | '/soy-profesional'
    | '/auth/crear-cuenta'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/futuro/centros-organizadores'
    | '/futuro/plan-presencia'
    | '/futuro/profesional-verificado'
    | '/invitacion/$token'
  id:
    | '__root__'
    | '/'
    | '/comunidad-fundadora'
    | '/comunidad-fundadora-organizaciones'
    | '/dashboard'
    | '/lista-espera'
    | '/plan-presencia'
    | '/profesional-fundador'
    | '/soy-profesional'
    | '/auth/crear-cuenta'
    | '/dashboard/formulario'
    | '/dashboard/perfil-publicado'
    | '/dashboard/solicitud-enviada'
    | '/dashboard/stripe'
    | '/futuro/centros-organizadores'
    | '/futuro/plan-presencia'
    | '/futuro/profesional-verificado'
    | '/invitacion/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComunidadFundadoraRoute: typeof ComunidadFundadoraRoute
  ComunidadFundadoraOrganizacionesRoute: typeof ComunidadFundadoraOrganizacionesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ListaEsperaRoute: typeof ListaEsperaRoute
  PlanPresenciaRoute: typeof PlanPresenciaRoute
  ProfesionalFundadorRoute: typeof ProfesionalFundadorRoute
  SoyProfesionalRoute: typeof SoyProfesionalRoute
  AuthCrearCuentaRoute: typeof AuthCrearCuentaRoute
  FuturoCentrosOrganizadoresRoute: typeof FuturoCentrosOrganizadoresRoute
  FuturoPlanPresenciaRoute: typeof FuturoPlanPresenciaRoute
  FuturoProfesionalVerificadoRoute: typeof FuturoProfesionalVerificadoRoute
  InvitacionTokenRoute: typeof InvitacionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soy-profesional': {
      id: '/soy-profesional'
      path: '/soy-profesional'
      fullPath: '/soy-profesional'
      preLoaderRoute: typeof SoyProfesionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional-fundador': {
      id: '/profesional-fundador'
      path: '/profesional-fundador'
      fullPath: '/profesional-fundador'
      preLoaderRoute: typeof ProfesionalFundadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-presencia': {
      id: '/plan-presencia'
      path: '/plan-presencia'
      fullPath: '/plan-presencia'
      preLoaderRoute: typeof PlanPresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista-espera': {
      id: '/lista-espera'
      path: '/lista-espera'
      fullPath: '/lista-espera'
      preLoaderRoute: typeof ListaEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora-organizaciones': {
      id: '/comunidad-fundadora-organizaciones'
      path: '/comunidad-fundadora-organizaciones'
      fullPath: '/comunidad-fundadora-organizaciones'
      preLoaderRoute: typeof ComunidadFundadoraOrganizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad-fundadora': {
      id: '/comunidad-fundadora'
      path: '/comunidad-fundadora'
      fullPath: '/comunidad-fundadora'
      preLoaderRoute: typeof ComunidadFundadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitacion/$token': {
      id: '/invitacion/$token'
      path: '/invitacion/$token'
      fullPath: '/invitacion/$token'
      preLoaderRoute: typeof InvitacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro/profesional-verificado': {
      id: '/futuro/profesional-verificado'
      path: '/futuro/profesional-verificado'
      fullPath: '/futuro/profesional-verificado'
      preLoaderRoute: typeof FuturoProfesionalVerificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro/plan-presencia': {
      id: '/futuro/plan-presencia'
      path: '/futuro/plan-presencia'
      fullPath: '/futuro/plan-presencia'
      preLoaderRoute: typeof FuturoPlanPresenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/futuro/centros-organizadores': {
      id: '/futuro/centros-organizadores'
      path: '/futuro/centros-organizadores'
      fullPath: '/futuro/centros-organizadores'
      preLoaderRoute: typeof FuturoCentrosOrganizadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stripe': {
      id: '/dashboard/stripe'
      path: '/stripe'
      fullPath: '/dashboard/stripe'
      preLoaderRoute: typeof DashboardStripeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/solicitud-enviada': {
      id: '/dashboard/solicitud-enviada'
      path: '/solicitud-enviada'
      fullPath: '/dashboard/solicitud-enviada'
      preLoaderRoute: typeof DashboardSolicitudEnviadaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/perfil-publicado': {
      id: '/dashboard/perfil-publicado'
      path: '/perfil-publicado'
      fullPath: '/dashboard/perfil-publicado'
      preLoaderRoute: typeof DashboardPerfilPublicadoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/formulario': {
      id: '/dashboard/formulario'
      path: '/formulario'
      fullPath: '/dashboard/formulario'
      preLoaderRoute: typeof DashboardFormularioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/crear-cuenta': {
      id: '/auth/crear-cuenta'
      path: '/auth/crear-cuenta'
      fullPath: '/auth/crear-cuenta'
      preLoaderRoute: typeof AuthCrearCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardFormularioRoute: typeof DashboardFormularioRoute
  DashboardPerfilPublicadoRoute: typeof DashboardPerfilPublicadoRoute
  DashboardSolicitudEnviadaRoute: typeof DashboardSolicitudEnviadaRoute
  DashboardStripeRoute: typeof DashboardStripeRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFormularioRoute: DashboardFormularioRoute,
  DashboardPerfilPublicadoRoute: DashboardPerfilPublicadoRoute,
  DashboardSolicitudEnviadaRoute: DashboardSolicitudEnviadaRoute,
  DashboardStripeRoute: DashboardStripeRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComunidadFundadoraRoute: ComunidadFundadoraRoute,
  ComunidadFundadoraOrganizacionesRoute: ComunidadFundadoraOrganizacionesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ListaEsperaRoute: ListaEsperaRoute,
  PlanPresenciaRoute: PlanPresenciaRoute,
  ProfesionalFundadorRoute: ProfesionalFundadorRoute,
  SoyProfesionalRoute: SoyProfesionalRoute,
  AuthCrearCuentaRoute: AuthCrearCuentaRoute,
  FuturoCentrosOrganizadoresRoute: FuturoCentrosOrganizadoresRoute,
  FuturoPlanPresenciaRoute: FuturoPlanPresenciaRoute,
  FuturoProfesionalVerificadoRoute: FuturoProfesionalVerificadoRoute,
  InvitacionTokenRoute: InvitacionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
